### ISSUE TITLE
Image cant be built with Dockerfile

### ISSUE THREAD

**Issue by sam-sre** [nacho270/docker-k8s-helm-demo#1]
Hi,

The `docker build` command requires the argument (`--build-arg JAR_FILE=build/libs/docker-k8s-helm-demo-1.0-SNAPSHOT.jar`) to build the image.
But this directory doesn't exists in the root dir of the repo and therefore the image cant be built.

Also when I run the `gradle build jar` command, I get this error:

```
Starting a Gradle Daemon (subsequent builds will be faster)

FAILURE: Build failed with an exception.

* Where:
Build file '/home/ubuntu/docker-k8s-helm-demo/build.gradle' line: 3

* What went wrong:
Plugin [id: 'com.palantir.docker', version: '0.26.0'] was not found in any of the following sources:

- Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
- Plugin Repositories (could not resolve plugin artifact 'com.palantir.docker:com.palantir.docker.gradle.plugin:0.26.0')
  Searched in the following repositories:
    Gradle Central Plugin Repository

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 13s
```

**Comment by nacho270** [comment]
Which version of gradle are you using?

**Comment by sam-sre** [comment]
Gradle 4.4.1

**Comment by nacho270** [comment]
Try upgrading to the latest version. As you can see [here](https://plugins.gradle.org/plugin/com.palantir.docker), the plugin exists but there's a newer syntax which is what i'm using.

**Comment by sam-sre** [comment]
I upgraded to Gradle 6.8.3 and still having the same issue.

Shouldn't `docker build --build-arg JAR_FILE=build/libs/docker-k8s-helm-demo-1.0-SNAPSHOT.jar` just work ?

**Comment by nacho270** [comment]
No, you first need to run `gradle build jar`. That command will create the build directory with the `libs/docker-k8s-helm-demo-1.0-SNAPSHOT.jar` inside.
